### ISSUE TITLE
ContactManager Error: type 'Null' is not a subtype of type 'String' of 'other'

### ISSUE THREAD

**Issue by jpribyl** [BlueBubblesApp/bluebubbles-app#1635]
Contacts are not loading for me

I'm not really a dart dev, but my gut here is that it's hitting a malformed contact entry and unable to skip over it:

```
flutter: [BlueBubblesApp][2021-10-23 16:34:06.775652][INFO] (REQUEST[GET]) -> PATH: http://192.168.1.179:1234/api/v1/contact
flutter: [BlueBubblesApp][2021-10-23 16:34:06.849787][INFO] Progress: 8% of the attachment
flutter: [BlueBubblesApp][2021-10-23 16:34:06.849891][INFO] Added process with id 9245 because Attachment downloader 614141AA-3D63-4905-BA62-4296E6459BCF
flutter: [BlueBubblesApp][2021-10-23 16:34:06.850088][INFO] (MessageBloc) -> No message chunks left from server
flutter: [BlueBubblesApp][2021-10-23 16:34:06.850114][INFO] (MessageBloc) -> Emitting 0 messages to listeners
flutter: [BlueBubblesApp][2021-10-23 16:34:06.850171][INFO] (MessageBloc) -> No more messages to load
flutter: [BlueBubblesApp][2021-10-23 16:34:07.109031][INFO] (RESPONSE[200]) -> PATH: http://192.168.1.179:1234/api/v1/contact
flutter: type 'Null' is not a subtype of type 'String' of 'other'
flutter: #0      ContactManager.getContacts (package:bluebubbles/managers/contact_manager.dart:135)
<asynchronous suspension>
#1      SetupBloc.finishSetup (package:bluebubbles/blocs/setup_bloc.dart:245)
<asynchronous suspension>
```

**Comment by tneotia** [comment]
@jjoelj actually found this issue and fixed it a couple days ago so the next desktop update will finally have actual contacts sync. And yes, your guess was correct, we just didn't have good enough null catching and it would throw an exception when parsing the JSON.
