### ISSUE TITLE
can't send audio recorded messages

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#2122]
```[BlueBubblesApp][2022-06-10 20:16:09.398757][ERROR] Failed to handle queued item! FileSystemException: Cannot open file, path = '/data/user/0/com.bluebubbles.messaging/files/attachments/OutgoingAudioMessage.m4a' (OS Error: No such file or directory, errno = 2)
[BlueBubblesApp][2022-06-10 20:16:09.398885][ERROR] #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356)
#1      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
#2      AttachmentSender.send (package:bluebubbles/helpers/attachment_sender.dart:53)
<asynchronous suspension>
#3      OutgoingQueue.handleQueueItem (package:bluebubbles/managers/outgoing_queue.dart:28)
<asynchronous suspension>
#4      QueueManager.processNextItem (package:bluebubbles/managers/queue_manager.dart:41)
<asynchronous suspension>```

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#support`.

**Comment by zlshames** [comment]
Seems like a client issue to me, not server

**Comment by tneotia** [comment]
Correct, I initially thought they meant incoming audio messages were broken
