### ISSUE TITLE
Segfault on launching v1.10.0-beta-1 on Ubuntu 22.04

### ISSUE THREAD

**Issue by Morpheus636** [BlueBubblesApp/bluebubbles-app#2213]
Here is the output when run from a terminal. Running v1.10.0-beta-1 on Ubuntu 22.04

installed using bluebubbles_linux.zip from the release and linux/install.sh

```
josh@josh-framework:~/Downloads$ bluebubbles
flutter: [BlueBubblesApp][2022-08-05 10:04:38.618970][INFO] Startup Logs
flutter: [BlueBubblesApp][2022-08-05 10:04:38.621493][INFO] Opening ObjectBox store from path: /home/josh/.local/share/app.bluebubbles.BlueBubbles/objectbox
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Bad state: Font should already be cached to be loaded
#0      RawDynamicCachedFonts.loadCachedFont (package:dynamic_cached_fonts/src/raw_dynamic_cached_fonts.dart:145)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method opacity on channel secure_application)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165)
<asynchronous suspension>

flutter: [BlueBubblesApp][2022-08-05 10:04:38.835942][ERROR] MissingPluginException(No implementation found for method listen on channel flutter_keyboard_visibility)
flutter: [BlueBubblesApp][2022-08-05 10:04:38.836028][ERROR] #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165)
flutter: <asynchronous suspension>
flutter: #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:506)
flutter: <asynchronous suspension>
flutter: 
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method listen on channel flutter_keyboard_visibility)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:506)
<asynchronous suspension>


(bluebubbles:79582): Gdk-CRITICAL **: 10:04:38.873: gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed

(bluebubbles:79582): Gdk-CRITICAL **: 10:04:38.873: gdk_monitor_get_workarea: assertion 'GDK_IS_MONITOR (monitor)' failed

(bluebubbles:79582): Gdk-CRITICAL **: 10:04:38.873: gdk_monitor_get_model: assertion 'GDK_IS_MONITOR (monitor)' failed

(bluebubbles:79582): Gdk-CRITICAL **: 10:04:38.873: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed
Segmentation fault (core dumped)
```

**Comment by llui85** [comment]
Can also reproduce on Debian 11.

**Comment by llui85** [comment]
Seems to be a problem with Wayland. In the meantime, it can be worked around by setting `GDK_BACKEND` to `X11`.

    GDK_BACKEND=X11 ./bluebubbles_app

**Comment by zlshames** [comment]
Thanks for the workaround!

**Comment by Morpheus636** [comment]
Don't close it - this is still an active bug. A workaround is not a fix.

**Comment by zlshames** [comment]
> Don't close it - this is still an active bug. A workaround is not a fix. 

Yup, totally. I meant more leaving it open until there is an update/full fix

**Comment by Morpheus636** [comment]
Ok, just wanted to make sure.

**Comment by richardbowman** [comment]
Would be awesome to see Wayland supported!! BlueBubbles is one of my last apps not handling fractional scaling well using Wayland.
