### ISSUE TITLE
music theme song changing breaks convo list gradient

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#2238]
Here is the error. It occurs over and over again

```
[BlueBubblesApp][2022-08-30 17:18:03.416436][ERROR] type 'Null' is not a subtype of type 'double' in type cast
[BlueBubblesApp][2022-08-30 17:18:03.416571][ERROR] #0      Movie.get (package:simple_animations/movie_tween/movie_tween.dart:369)
#1      ConversationViewState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:bluebubbles/layouts/conversation_view/conversation_view.dart:746)
#2      _CustomAnimationBuilderState.build (package:simple_animations/animation_builder/custom_animation_builder.dart:275)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4919)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4529)
#7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083)
#12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997)
#13     _rootRun (dart:async/zone.dart:1426)
#14     _CustomZone.run (dart:async/zone.dart:1328)
#15     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#16     _invoke (dart:ui/hooks.dart:151)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308)
#18     _drawFrame (dart:ui/hooks.dart:115)
```

**Comment by zlshames** [comment]
More info from MisplacedMonkey

```
Yeah, so basically - the chat window will turn grey.  I've noticed that this only occurs in the chat window and not anywhere else in the app.  I haven't been able to find out exactly what reproduces it.  It has happened while I was actively texting someone, when I switched to a different messaging thread, when I opened another app and then returned to bluebubbles, when I was trying to share a photo from another app (Gallery or Reddit is fun), and after exiting and reentering a messaging thread.
```

```
I noticed that I have music theme selected.  So I changed the song that was playing and this caused the bug to reproduce
```

The issue is caused by a null value when calculating the tween values for the gradient background in the message view

**Comment by zlshames** [comment]
![CleanShot 2022-08-31 at 09 05 20](https://user-images.githubusercontent.com/18445938/187685226-cefc1104-8666-4e86-8abd-6ca1312ecb69.png)
