### ISSUE TITLE
[Android 8] Fingerprint Unlock causes app crash

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#2339]
The error:

```
01-26 06:11:08.125  1000  3844  3844 W FingerprintService: client com.bluebubbles.messaging is authenticating...
01-26 06:11:08.146 10139 26915 26915 E AndroidRuntime: FATAL EXCEPTION: main
01-26 06:11:08.146 10139 26915 26915 E AndroidRuntime: Process: com.bluebubbles.messaging, PID: 26915
01-26 06:11:08.146 10139 26915 26915 E AndroidRuntime: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
01-26 06:11:08.146 10139 26915 26915 E AndroidRuntime:     at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:856)
01-26 06:11:08.146 10139 26915 26915 E AndroidRuntime:     at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:819)
01-26 06:11:08.146 10139 26915 26915 E AndroidRuntime:     at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:707)
01-26 06:11:08.146 10139 26915 26915 E AndroidRuntime:     at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
01-26 06:11:08.146 10139 26915 26915 E AndroidRuntime:     at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
01-26 06:11:08.146 10139 26915 26915 E AndroidRuntime:     at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
01-26 06:11:08.146 10139 26915 26915 E AndroidRuntime:     at android.app.Dialog.dispatchOnCreate(Dialog.java:403)
01-26 06:11:08.146 10139 26915 26915 E AndroidRuntime:     at android.app.Dialog.show(Dialog.java:302)
01-26 06:11:08.146 10139 26915 26915 E AndroidRuntime:     at androidx.fragment.app.DialogFragment.onStart(DialogFragment.java:728)
```

**Comment by zlshames** [comment]
seems like an issue with the local_auth package. Not sure there is an update to fix it.
