### ISSUE TITLE
Fix crash when loading certain backups

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#2492]
```
06-01 22:07:34.465 10358 31314 31314 E AndroidRuntime: FATAL EXCEPTION: main
06-01 22:07:34.465 10358 31314 31314 E AndroidRuntime: Process: com.bluebubbles.messaging, PID: 31314
06-01 22:07:34.465 10358 31314 31314 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
06-01 22:07:34.465 10358 31314 31314 E AndroidRuntime: 	at com.bluebubbles.messaging.services.FirebaseMessagingService$1.success(FirebaseMessagingService.java:71)
06-01 22:07:34.465 10358 31314 31314 E AndroidRuntime: 	at com.bluebubbles.messaging.method_call_handler.handlers.GetServerUrl$1.onComplete(GetServerUrl.java:50)
06-01 22:07:34.465 10358 31314 31314 E AndroidRuntime: 	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
06-01 22:07:34.465 10358 31314 31314 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
06-01 22:07:34.465 10358 31314 31314 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-01 22:07:34.465 10358 31314 31314 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:240)
06-01 22:07:34.465 10358 31314 31314 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:351)
06-01 22:07:34.465 10358 31314 31314 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8380)
06-01 22:07:34.465 10358 31314 31314 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-01 22:07:34.465 10358 31314 31314 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
06-01 22:07:34.465 10358 31314 31314 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

Video of bug: https://discord.com/channels/640229510662455326/746560644995612752/1114014827661250621

The issue happens when the QRCode scan is cancelled, and null is returned and "used" as the server URL, which gets attempted to be sent to Tasker (when enabled)

**Comment by zlshames** [comment]
The error is in this block of code: https://github.com/BlueBubblesApp/bluebubbles-app/blob/master/android/app/src/main/java/com/bluebubbles/messaging/services/FirebaseMessagingService.java#L65-L75

It seems like the issue is when Send Events to Tasker is enabled. Oddly, it has to do with firebase, and for some reason the `getServerUrl()` response value is null

**Comment by zlshames** [comment]
Fixed by preventing a null value from executing code to forward to tasker
