### ISSUE TITLE
Android crash on initial setup if it cannot resolve firebaselogging.google.com and others

### ISSUE THREAD

**Issue by working-name** [BlueBubblesApp/bluebubbles-app#2579]
Hello there,

Not sure how to log the problems, went to troubleshooting and then started logging but that doesn't persist once the app crashes. It seems to crash on a timer - around 30 seconds or so. That makes me think networking.

Is java so crappy that it crashes when it can't connect to something? How do I debug this? And why didn't it crash when it was first syncing with the server?

**Comment by zlshames** [comment]
@working-name no, it should not crash if a connection fails. That isn't intended or normal. My initial thought is possibly an invalid device token of some sort. Try the following:

1. Backup your app settings (if you can)
2. On the server, clear your devices from the android notifications tab
3. On the app, clear its' storage using the Android settings for storage
4. Resync the app by reconfiguring it with your server
5. Restore settings.

Not sure what happened with your setup, but something broke. Only other option if you want to avoid an app-storage clear would be to get an Interactive Bug report via Android Developer options

**Comment by working-name** [comment]
Interesting. Well, since it's the first time I ever set up BB, I don't mind blowing the app. Also, don't know if it matters - I do not have a google account linked (play store prompts me to login). I usually get my apps via Aurora but since it's acting up today I got the APK from releases.

> 1. Backup your app settings (if you can)

Done. 
> 2. On the server, clear your devices from the android notifications tab

I don't see it there, might be related to the fact that I'm not logged in to a google account on my android phone? Or maybe because I set up the app using the QR code?

> 3. On the app, clear its' storage using the Android settings for storage

Force quit, clear data. Done.
> 4. Resync the app by reconfiguring it with your server

Done, with default last 25 messages. On the sync complete page, after the confetti animation the app crashed.
> 5. Restore settings.

Done.
> get an Interactive Bug report via Android Developer options

ran `adb logcat --uid=10542 com.bluebubbles.messaging` but it pushes out a lot of sensitive info including phone numbers. Here's some pertinent excerpts:

```python
10-30 14:30:26.062  3429  3429 D AndroidRuntime: Shutting down VM
10-30 14:30:26.062  3429  3429 E AndroidRuntime: FATAL EXCEPTION: main
10-30 14:30:26.062  3429  3429 E AndroidRuntime: Process: com.bluebubbles.messaging, PID: 3429
10-30 14:30:26.062  3429  3429 E AndroidRuntime: com.google.android.gms.tasks.RuntimeExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzw.getResult(com.google.android.gms:play-services-tasks@@18.0.2:3)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.bluebubbles.messaging.method_call_handler.handlers.FirebaseAuth$1.onComplete(FirebaseAuth.java:63)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8762)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: Caused by: java.io.IOException: SERVICE_NOT_AVAILABLE
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.firebase.iid.GmsRpc.handleResponse(com.google.firebase:firebase-iid@@21.1.0:7)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.firebase.iid.GmsRpc.lambda$extractResponseWhenComplete$0$GmsRpc(com.google.firebase:firebase-iid@@21.1.0:1)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.firebase.iid.GmsRpc$$Lambda$0.then(Unknown Source:2)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.2:3)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.firebase.iid.FirebaseIidExecutors$$Lambda$0.execute(Unknown Source:0)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.2:1)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.2:5)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.2:3)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.2:8)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.cloudmessaging.zzz.execute(Unknown Source:0)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.2:1)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.2:5)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.2:3)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.TaskCompletionSource.setResult(com.google.android.gms:play-services-tasks@@18.0.2:1)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.cloudmessaging.zzp.zzd(com.google.android.gms:play-services-cloud-messaging@@17.0.0:3)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.cloudmessaging.zzr.zza(com.google.android.gms:play-services-cloud-messaging@@17.0.0:2)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.cloudmessaging.zzf.handleMessage(com.google.android.gms:play-services-cloud-messaging@@17.0.0:14)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	... 6 more
```

Crashing because it can't resolve firebaselogging.googleapis.com (I run RethinkDNS and the hostname is on 3 different block lists):
![photo_2023-10-30 14 55 40](https://github.com/BlueBubblesApp/bluebubbles-app/assets/16505052/6cb4f31a-09f4-4177-a491-bf03db844016)


```python
10-30 14:30:25.317  3429  3483 I flutter : [BlueBubblesApp][2023-10-30 14:30:22.426292][DEBUG] Creating chat controller for iMessage;+;chat645542182315384162 ()
10-30 14:30:26.061  3429  8540 W FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE. Will retry token retrieval
10-30 14:30:26.062  3429  3429 D AndroidRuntime: Shutting down VM
10-30 14:30:26.062  3429  3429 E AndroidRuntime: FATAL EXCEPTION: main
10-30 14:30:26.062  3429  3429 E AndroidRuntime: Process: com.bluebubbles.messaging, PID: 3429
10-30 14:30:26.062  3429  3429 E AndroidRuntime: com.google.android.gms.tasks.RuntimeExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzw.getResult(com.google.android.gms:play-services-tasks@@18.0.2:3)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.bluebubbles.messaging.method_call_handler.handlers.FirebaseAuth$1.onComplete(FirebaseAuth.java:63)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8762)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: Caused by: java.io.IOException: SERVICE_NOT_AVAILABLE
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.firebase.iid.GmsRpc.handleResponse(com.google.firebase:firebase-iid@@21.1.0:7)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.firebase.iid.GmsRpc.lambda$extractResponseWhenComplete$0$GmsRpc(com.google.firebase:firebase-iid@@21.1.0:1)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.firebase.iid.GmsRpc$$Lambda$0.then(Unknown Source:2)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.2:3)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.firebase.iid.FirebaseIidExecutors$$Lambda$0.execute(Unknown Source:0)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.2:1)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.2:5)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.2:3)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.2:8)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.cloudmessaging.zzz.execute(Unknown Source:0)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.2:1)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.2:5)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.2:3)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.tasks.TaskCompletionSource.setResult(com.google.android.gms:play-services-tasks@@18.0.2:1)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.cloudmessaging.zzp.zzd(com.google.android.gms:play-services-cloud-messaging@@17.0.0:3)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.cloudmessaging.zzr.zza(com.google.android.gms:play-services-cloud-messaging@@17.0.0:2)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at com.google.android.gms.cloudmessaging.zzf.handleMessage(com.google.android.gms:play-services-cloud-messaging@@17.0.0:14)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-30 14:30:26.062  3429  3429 E AndroidRuntime: 	... 6 more
10-30 14:30:26.086  3429  3429 I Process : Sending signal. PID: 3429 SIG: 9
10-30 14:32:12.411  9373  9373 I bbles.messaging: Using CollectorTypeCC GC.
10-30 14:32:12.414  9373  9373 E bbles.messaging: Not starting debugger since process cannot load the jdwp agent.
10-30 14:32:12.419  9373  9373 D ActivityThread: setConscryptValidator
10-30 14:32:12.419  9373  9373 D ActivityThread: setConscryptValidator - put
10-30 14:32:12.425  9373  9373 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10542; state: ENABLED
10-30 14:32:12.430  9373  9373 D nativeloader: Configuring classloader-namespace for other apk /data/app/~~TzmXDVvoLCB1iPxWTyFXLQ==/com.bluebubbles.messaging-RAkCbku7veOPm0SxMq6bIQ==/base.apk. target_sdk_version=33, uses_libraries=libOpenCL.so, library_path=/data/app/~~TzmXDVvoLCB1iPxWTyFXLQ==/com.bluebubbles.messaging-RAkCbku7veOPm0SxMq6bIQ==/lib/arm64:/data/app/~~TzmXDVvoLCB1iPxWTyFXLQ==/com.bluebubbles.messaging-RAkCbku7veOPm0SxMq6bIQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.bluebubbles.messaging
10-30 14:32:12.436  9373  9373 V GraphicsEnvironment: ANGLE Developer option for 'com.bluebubbles.messaging' set to: 'default'
10-30 14:32:12.436  9373  9373 V GraphicsEnvironment: ANGLE GameManagerService for com.bluebubbles.messaging: false
10-30 14:32:12.436  9373  9373 V GraphicsEnvironment: App is not on the allowlist for updatable production driver.
10-30 14:32:12.437  9373  9373 D NetworkSecurityConfig: No Network Security Config specified, using platform default
10-30 14:32:12.439  9373  9373 D NetworkSecurityConfig: No Network Security Config specified, using platform default
10-30 14:32:12.446  9373  9373 D DIRecoRegistrar: DigitalInkRecognitionRegistrar.getComponents()
10-30 14:32:12.456  9373  9373 D WM-WrkMgrInitializer: Initializing WorkManager with default configuration.
10-30 14:32:12.492  9373  9405 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10542; state: ENABLED
10-30 14:32:12.519  9373  9411 I TRuntime.CctTransportBackend: Making request to: https://firebaselogging.googleapis.com/v0cc/log/batch?format=json_proto3
10-30 14:32:12.535  9373  9411 D TrafficStats: tagSocket(89) with statsTag=0xffffffff, statsUid=-1
10-30 14:32:12.541  9373  9411 E TRuntime.CctTransportBackend: Couldn't open connection, returning with 500
10-30 14:32:12.541  9373  9411 E TRuntime.CctTransportBackend: java.net.ConnectException: Failed to connect to firebaselogging.googleapis.com/0.0.0.0:443
```

And one more crash, service not available, but still failing to connect to firebaselogging.googleapis.com:

```python
10-30 14:38:04.453  9373 11098 I flutter : [BlueBubblesApp][2023-10-30 14:37:56.793710][DEBUG] Creating chat controller for iMessage;-;+11231234123 ()
10-30 14:38:04.453  9373 11098 I flutter : [BlueBubblesApp][2023-10-30 14:37:56.798679][INFO] (ChatBloc) -> Finished fetching chats (985).
10-30 14:38:04.453  9373 11098 I flutter : [BlueBubblesApp][2023-10-30 14:37:57.694804][INFO] (FCM-Auth) -> Authenticating with FCM
10-30 14:38:05.819  9373  9373 D AndroidRuntime: Shutting down VM
10-30 14:38:05.819  9373 11178 W FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE. Will retry token retrieval
10-30 14:38:05.820  9373  9373 E AndroidRuntime: FATAL EXCEPTION: main
10-30 14:38:05.820  9373  9373 E AndroidRuntime: Process: com.bluebubbles.messaging, PID: 9373
10-30 14:38:05.820  9373  9373 E AndroidRuntime: com.google.android.gms.tasks.RuntimeExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.android.gms.tasks.zzw.getResult(com.google.android.gms:play-services-tasks@@18.0.2:3)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.bluebubbles.messaging.method_call_handler.handlers.FirebaseAuth$1.onComplete(FirebaseAuth.java:63)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8762)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: Caused by: java.io.IOException: SERVICE_NOT_AVAILABLE
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.firebase.iid.GmsRpc.handleResponse(com.google.firebase:firebase-iid@@21.1.0:7)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.firebase.iid.GmsRpc.lambda$extractResponseWhenComplete$0$GmsRpc(com.google.firebase:firebase-iid@@21.1.0:1)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.firebase.iid.GmsRpc$$Lambda$0.then(Unknown Source:2)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.2:3)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.firebase.iid.FirebaseIidExecutors$$Lambda$0.execute(Unknown Source:0)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.2:1)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.2:5)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.2:3)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.2:8)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.android.gms.cloudmessaging.zzz.execute(Unknown Source:0)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.2:1)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.2:5)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.2:3)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.android.gms.tasks.TaskCompletionSource.setResult(com.google.android.gms:play-services-tasks@@18.0.2:1)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.android.gms.cloudmessaging.zzp.zzd(com.google.android.gms:play-services-cloud-messaging@@17.0.0:3)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.android.gms.cloudmessaging.zzr.zza(com.google.android.gms:play-services-cloud-messaging@@17.0.0:2)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at com.google.android.gms.cloudmessaging.zzf.handleMessage(com.google.android.gms:play-services-cloud-messaging@@17.0.0:14)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-30 14:38:05.820  9373  9373 E AndroidRuntime: 	... 6 more
10-30 14:38:05.859  9373  9373 I Process : Sending signal. PID: 9373 SIG: 9
10-30 14:46:21.612 12400 12400 I bbles.messaging: Using CollectorTypeCC GC.
10-30 14:46:21.617 12400 12400 E bbles.messaging: Not starting debugger since process cannot load the jdwp agent.
10-30 14:46:21.632 12400 12400 D ActivityThread: setConscryptValidator
10-30 14:46:21.632 12400 12400 D ActivityThread: setConscryptValidator - put
10-30 14:46:21.642 12400 12400 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10542; state: ENABLED
10-30 14:46:21.652 12400 12400 D nativeloader: Configuring classloader-namespace for other apk /data/app/~~TzmXDVvoLCB1iPxWTyFXLQ==/com.bluebubbles.messaging-RAkCbku7veOPm0SxMq6bIQ==/base.apk. target_sdk_version=33, uses_libraries=libOpenCL.so, library_path=/data/app/~~TzmXDVvoLCB1iPxWTyFXLQ==/com.bluebubbles.messaging-RAkCbku7veOPm0SxMq6bIQ==/lib/arm64:/data/app/~~TzmXDVvoLCB1iPxWTyFXLQ==/com.bluebubbles.messaging-RAkCbku7veOPm0SxMq6bIQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.bluebubbles.messaging
10-30 14:46:21.662 12400 12400 V GraphicsEnvironment: ANGLE Developer option for 'com.bluebubbles.messaging' set to: 'default'
10-30 14:46:21.662 12400 12400 V GraphicsEnvironment: ANGLE GameManagerService for com.bluebubbles.messaging: false
10-30 14:46:21.662 12400 12400 V GraphicsEnvironment: App is not on the allowlist for updatable production driver.
10-30 14:46:21.666 12400 12400 D NetworkSecurityConfig: No Network Security Config specified, using platform default
10-30 14:46:21.669 12400 12400 D NetworkSecurityConfig: No Network Security Config specified, using platform default
10-30 14:46:21.679 12400 12400 D DIRecoRegistrar: DigitalInkRecognitionRegistrar.getComponents()
10-30 14:46:21.692 12400 12400 D WM-WrkMgrInitializer: Initializing WorkManager with default configuration.
10-30 14:46:21.753 12400 12482 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10542; state: ENABLED
10-30 14:46:21.803 12400 12487 I TRuntime.CctTransportBackend: Making request to: https://firebaselogging.googleapis.com/v0cc/log/batch?format=json_proto3
10-30 14:46:21.812 12400 12487 D TrafficStats: tagSocket(89) with statsTag=0xffffffff, statsUid=-1
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: Couldn't open connection, returning with 500
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: java.net.ConnectException: Failed to connect to firebaselogging.googleapis.com/0.0.0.0:443
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.google.android.datatransport.cct.CctTransportBackend.doSend(CctTransportBackend.java:303)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.google.android.datatransport.cct.CctTransportBackend.$r8$lambda$bLAzIpNF4NtapXlUpPVGhzxyNT8(Unknown Source:0)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.google.android.datatransport.cct.CctTransportBackend$$ExternalSyntheticLambda0.apply(Unknown Source:4)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.google.android.datatransport.runtime.retries.Retries.retry(Retries.java:54)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.google.android.datatransport.cct.CctTransportBackend.send(CctTransportBackend.java:372)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.logAndUpdateState(Uploader.java:146)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.lambda$upload$1$com-google-android-datatransport-runtime-scheduling-jobscheduling-Uploader(Uploader.java:105)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader$$ExternalSyntheticLambda1.run(Unknown Source:8)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at com.google.android.datatransport.runtime.SafeLoggingExecutor$SafeLoggingRunnable.run(SafeLoggingExecutor.java:47)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-30 14:46:21.816 12400 12487 E TRuntime.CctTransportBackend: 	at java.lang.Thread.run(Thread.java:1012)
10-30 14:46:21.819 12400 12487 D CompatibilityChangeReporter: Compat change id reported: 194532703; UID 10542; state: ENABLED
10-30 14:46:27.089 12400 13470 D ProfileInstaller: Skipping profile installation for com.bluebubbles.messaging
```

**Comment by zlshames** [comment]
First, thank you for being so in-depth... Much appreciated.

Second, yeah, it definitely looks like it's being blocked. Do you mind adding it to your whitelist? Then see if the issue persists. We should probably prevent it from crashing though, so I'm going to keep this ticket open

**Comment by working-name** [comment]
I whitelisted firebaselogging. but the app still crashed. However, it doesn't mention another hostname. I disabled RethinkDNS and it no longer crashes. So it's all of the setup with firebase and/or notifications that crashes the app until it completes. The phone now shows up in the server under android devices, too.

I've re-enabled RethinkDNS and while I don't get notifications (I can figure out what hostnames to whitelist later), the app no longer crashes.

**Comment by zlshames** [comment]
> I whitelisted firebaselogging. but the app still crashed. However, it doesn't mention another hostname. I disabled RethinkDNS and it no longer crashes. So it's all of the setup with firebase and/or notifications that crashes the app until it completes. The phone now shows up in the server under android devices, too.
> 
> I've re-enabled RethinkDNS and while I don't get notifications (I can figure out what hostnames to whitelist later), the app no longer crashes.

I bet whitelisting it worked, but your DNS cache just needed to be flushed. So by disconnecting it entirely, then reconnecting it was flushed maybe
