### ISSUE TITLE
Consistent error using FindMy on Android

### ISSUE THREAD

**Issue by masnax** [BlueBubblesApp/bluebubbles-app#2592]
After updating to 1.12.5, I'm getting this stack trace whenever I open FindMy:

Since I'm using the built-in logger, the full flow is 
* Return to main screen
* Go to FindMy via the dropdown
* Exit FindMy
* Return to settings to save the log

```
[BlueBubblesApp][2023-12-01 15:02:46.235295][ERROR] UnimplementedError: appWindow has not been implemented.
[BlueBubblesApp][2023-12-01 15:02:46.235652][ERROR] Stacktrace: #0      BitsdojoWindowPlatform.appWindow (package:bitsdojo_window_platform_interface/bitsdojo_window_platform_interface.dart:47)
#1      appWindow (package:bitsdojo_window/src/app_window.dart:42)
#2      _FindMyPageState.buildDesktop.<anonymous closure> (package:bluebubbles/app/layouts/findmy/findmy_page.dart:746)
#3      GestureRecognizerFactoryWithHandlers.constructor (package:flutter/src/widgets/gesture_detector.dart:103)
#4      RxInterface.notifyChildren (package:get/get_rx/src/rx_types/rx_core/rx_interface.dart:26)
#5      _ObxState.build (package:get/get_state_manager/src/rx_flutter/rx_obx_widget.dart:54)
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:5409)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5297)
#8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
#11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
#15     _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:135)
#16     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2719)
#17     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:153)
#18     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2604)
#19     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1059)
#20     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2604)
#21     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:228)
#22     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:313)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#24     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#27     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#30     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#33     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#36     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#38     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#39     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#42     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#45     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#46     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3730)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#48     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#51     RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#52     _RenderTheaterMixin.performLayout (package:flutter/src/widgets/overlay.dart:838)
#53     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2332)
#54     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1013)
#55     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:494)
#56     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918)
#57     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360)
#58     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297)
#59     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227)
#60     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085)
#61     _invoke (dart:ui/hooks.dart:170)
#62     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401)
#63     _drawFrame (dart:ui/hooks.dart:140)

[BlueBubblesApp][2023-12-01 15:02:46.244473][INFO] (REQUEST[GET]) -> PATH: http://192.168.1.167:1234/api/v1/icloud/findmy/devices
[BlueBubblesApp][2023-12-01 15:02:46.529954][INFO] (RESPONSE[200]) -> PATH: http://192.168.1.167:1234/api/v1/icloud/findmy/devices
[BlueBubblesApp][2023-12-01 15:02:46.530335][INFO] (REQUEST[GET]) -> PATH: http://192.168.1.167:1234/api/v1/icloud/findmy/friends
[BlueBubblesApp][2023-12-01 15:02:46.539589][INFO] (RESPONSE[200]) -> PATH: http://192.168.1.167:1234/api/v1/icloud/findmy/friends
[BlueBubblesApp][2023-12-01 15:02:47.789976][ERROR] LateInitializationError: Field '_state@1054197155' has not been initialized.
[BlueBubblesApp][2023-12-01 15:02:47.790027][ERROR] #0      MapControllerImpl.move (package:flutter_map/src/map/controller.dart)
#1      _FindMyPageState.getLocations (package:bluebubbles/app/layouts/findmy/findmy_page.dart:135)
<asynchronous suspension>

[BlueBubblesApp][2023-12-01 15:02:47.792837][ERROR] UnimplementedError: appWindow has not been implemented.
[BlueBubblesApp][2023-12-01 15:02:47.792979][ERROR] Stacktrace: #0      BitsdojoWindowPlatform.appWindow (package:bitsdojo_window_platform_interface/bitsdojo_window_platform_interface.dart:47)
#1      appWindow (package:bitsdojo_window/src/app_window.dart:42)
#2      _FindMyPageState.buildDesktop.<anonymous closure> (package:bluebubbles/app/layouts/findmy/findmy_page.dart:746)
#3      GestureRecognizerFactoryWithHandlers.constructor (package:flutter/src/widgets/gesture_detector.dart:103)
#4      RxInterface.notifyChildren (package:get/get_rx/src/rx_types/rx_core/rx_interface.dart:26)
#5      _ObxState.build (package:get/get_state_manager/src/rx_flutter/rx_obx_widget.dart:54)
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:5409)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5297)
#8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#10     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#12     _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:135)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2719)
#14     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:153)
#15     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2604)
#16     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1059)
#17     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2604)
#18     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:228)
#19     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:313)
#20     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2332)
#21     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1013)
#22     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:494)
#23     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918)
#24     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360)
#25     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297)
#26     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227)
#27     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085)
#28     _invoke (dart:ui/hooks.dart:170)
#29     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401)
#30     _drawFrame (dart:ui/hooks.dart:140)

[BlueBubblesApp][2023-12-01 15:02:47.809738][ERROR] UnimplementedError: appWindow has not been implemented.
[BlueBubblesApp][2023-12-01 15:02:47.809867][ERROR] Stacktrace: #0      BitsdojoWindowPlatform.appWindow (package:bitsdojo_window_platform_interface/bitsdojo_window_platform_interface.dart:47)
#1      appWindow (package:bitsdojo_window/src/app_window.dart:42)
#2      _FindMyPageState.buildDesktop.<anonymous closure> (package:bluebubbles/app/layouts/findmy/findmy_page.dart:746)
#3      GestureRecognizerFactoryWithHandlers.constructor (package:flutter/src/widgets/gesture_detector.dart:103)
#4      RxInterface.notifyChildren (package:get/get_rx/src/rx_types/rx_core/rx_interface.dart:26)
#5      _ObxState.build (package:get/get_state_manager/src/rx_flutter/rx_obx_widget.dart:54)
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:5409)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5297)
#8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#10     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#12     _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:135)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2719)
#14     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:153)
#15     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2604)
#16     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1059)
#17     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2604)
#18     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:228)
#19     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:313)
#20     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2332)
#21     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1013)
#22     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:494)
#23     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918)
#24     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360)
#25     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297)
#26     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227)
#27     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085)
#28     _invoke (dart:ui/hooks.dart:170)
#29     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401)
#30     _drawFrame (dart:ui/hooks.dart:140)
```

**Comment by jjoelj** [comment]
Are you on a tablet by any chance? I think I know what's causing this

**Comment by masnax** [comment]
Close enough, it's a Foldable :)

**Comment by zlshames** [comment]
We will likely release a hotfix for this and a few other bugs

**Comment by jjoelj** [comment]
Fixed in https://github.com/BlueBubblesApp/bluebubbles-app/commit/ae2f8e81a24dc62548b2f5ba15d164fe317731d4
